-- Vista Materializada 1 --

CREATE MATERIALIZED VIEW FIDE_DASHBOARD_TIPOS_AHORRO_VM
    BUILD IMMEDIATE
    REFRESH COMPLETE ON DEMAND
    AS
    WITH ESTADO_ACTIVO AS (
        SELECT ID_ESTADO 
        FROM FIDE_ESTADO_TB 
        WHERE UPPER(NOMBRE) = 'ACTIVO' 
        AND ROWNUM = 1
    )
    SELECT
        ta.ID_TIPO_AHORRO,
        ta.NOMBRE                                AS TIPO_AHORRO,
        COUNT(ca.ID_AHORRO)                      AS TOTAL_CUENTAS,
        NVL(SUM(ca.SALDO_ACTUAL), 0)             AS SALDO_TOTAL,
        NVL(AVG(ca.SALDO_ACTUAL), 0)             AS SALDO_PROMEDIO,
        ROUND(
            COUNT(ca.ID_AHORRO) * 100.0 
            / NULLIF(SUM(COUNT(ca.ID_AHORRO)) OVER (), 0), 
            2
        )                                        AS PORCENTAJE_CUENTAS
    FROM FIDE_TIPO_AHORRO_TB ta
    CROSS JOIN ESTADO_ACTIVO ea  
    LEFT JOIN FIDE_CUENTAS_AHORRO_TB ca 
        ON ta.ID_TIPO_AHORRO = ca.ID_TIPO_AHORRO 
        AND ca.ID_ESTADO = ea.ID_ESTADO 
    WHERE ta.ID_ESTADO = ea.ID_ESTADO
    GROUP BY 
        ta.ID_TIPO_AHORRO, 
        ta.NOMBRE;
/


-- Vista Materializada 2 --

CREATE MATERIALIZED VIEW FIDE_DASHBOARD_TRANSACCIONES_VM
    BUILD IMMEDIATE
    REFRESH COMPLETE ON DEMAND
    AS
SELECT
    TO_CHAR(t.FECHA_TRANSACCION, 'MON-YYYY') AS MES,
    TRUNC(t.FECHA_TRANSACCION, 'MM')          AS MES_ORDEN,
    tt.NOMBRE                                  AS TIPO,
    COUNT(*)                                   AS CANTIDAD,
    NVL(SUM(t.MONTO_TOTAL), 0)                AS MONTO_TOTAL
FROM FIDE_TRANSACCION_TB t
JOIN FIDE_TIPO_TRANSACCION_TB tt ON t.ID_TIPO_TRANSACCION = tt.ID_TIPO_TRANSACCION
WHERE t.FECHA_TRANSACCION >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -5)
GROUP BY
    TO_CHAR(t.FECHA_TRANSACCION, 'MON-YYYY'),
    TRUNC(t.FECHA_TRANSACCION, 'MM'),
    tt.NOMBRE
/


-- Vista Materializada 3 --

CREATE MATERIALIZED VIEW FIDE_HISTORIAL_TRANSACCIONES_VM
    BUILD IMMEDIATE
    REFRESH COMPLETE ON DEMAND
    AS
SELECT T.ID_TRANSACCION,
       T.FECHA_TRANSACCION,
       T.MONTO_TOTAL,
       U.ID_USUARIO,
       U.NOMBRE,
       U.APELLIDO_PATERNO
FROM FIDE_TRANSACCION_TB T,
     FIDE_USUARIO_TB U
WHERE T.ID_USUARIO = U.ID_USUARIO
/

-- Vista Materializada 4 --

CREATE MATERIALIZED VIEW FIDE_TOP_USUARIOS_TRANSACCIONES_VM
    BUILD IMMEDIATE
    REFRESH COMPLETE ON DEMAND
    AS
SELECT *
FROM (
    SELECT U.ID_USUARIO,
           U.NOMBRE,
           U.APELLIDO_PATERNO,
           COUNT(T.ID_TRANSACCION) AS TOTAL_TRANSACCIONES
    FROM FIDE_USUARIO_TB U,
         FIDE_TRANSACCION_TB T
    WHERE U.ID_USUARIO = T.ID_USUARIO
    GROUP BY U.ID_USUARIO, U.NOMBRE, U.APELLIDO_PATERNO
    ORDER BY TOTAL_TRANSACCIONES DESC
)
WHERE ROWNUM <= 5
/

-- Vista Materializada 5 --

CREATE MATERIALIZED VIEW FIDE_TOP10_MENOS_AHORROS_VM
    BUILD IMMEDIATE
    REFRESH COMPLETE ON DEMAND
    AS
SELECT *
FROM (
    SELECT U.ID_USUARIO,
           U.NOMBRE,
           U.APELLIDO_PATERNO,
           NVL(SUM(A.SALDO_ACTUAL), 0) AS TOTAL_AHORRO
    FROM FIDE_USUARIO_TB U
    LEFT JOIN FIDE_CUENTAS_AHORRO_TB A ON U.ID_USUARIO = A.ID_USUARIO
    GROUP BY U.ID_USUARIO, U.NOMBRE, U.APELLIDO_PATERNO
    ORDER BY TOTAL_AHORRO ASC
)
WHERE ROWNUM <= 10
/

-- Vista Materializada 6 --

CREATE MATERIALIZED VIEW FIDE_USUARIOS_ULTIMO_MES_VM
    BUILD IMMEDIATE
    REFRESH COMPLETE ON DEMAND
    AS
SELECT U.ID_USUARIO,
       U.NOMBRE,
       U.APELLIDO_PATERNO,
       U.APELLIDO_MATERNO,
       U.NOMBRE_USUARIO,
       D.FECHA_AFILIACION
FROM FIDE_USUARIO_TB U
JOIN FIDE_DATOS_ASOCIADOS_TB D ON U.ID_DATOS_ASOCIADOS = D.ID_DATOS_ASOCIADOS
WHERE D.FECHA_AFILIACION >= ADD_MONTHS(SYSDATE, -1)
/

