-------------------- INDICES --------------------

-- Indice FIDE_USUARIO_NOMBRE_UNIQUE_IDX
CREATE UNIQUE INDEX FIDE_USUARIO_NOMBRE_UNIQUE_IDX ON FIDE_USUARIO_TB(NOMBRE_USUARIO);

-- Indice FIDE_CORREO_ELECTRONICO_UNIQUE_IDX
CREATE UNIQUE INDEX FIDE_CORREO_ELECTRONICO_UNIQUE_IDX ON FIDE_CORREO_ELECTRONICO_TB(CORREO_ELECTRONICO);

-- Indice FIDE_NUMERO_TELEFONO_UNIQUE_IDX
CREATE UNIQUE INDEX FIDE_NUMERO_TELEFONO_UNIQUE_IDX ON FIDE_NUMERO_TELEFONO_TB(NUMERO_TELEFONO);

-- Indice FIDE_TRANSACCION_USUARIO_IDX
CREATE INDEX FIDE_TRANSACCION_USUARIO_IDX ON FIDE_TRANSACCION_TB(ID_USUARIO);

-- Indice FIDE_TRANSACCION_TIPO_IDX
CREATE INDEX FIDE_TRANSACCION_TIPO_IDX ON FIDE_TRANSACCION_TB(ID_TIPO_TRANSACCION);

-- Indice FIDE_DETALLE_TRANSACCION_IDX
CREATE INDEX FIDE_DETALLE_TRANSACCION_IDX ON FIDE_DETALLE_TRANSACCION_TB(ID_TRANSACCION);

-- Indice FIDE_CUENTAS_AHORRO_USUARIO_IDX
CREATE INDEX FIDE_CUENTAS_AHORRO_USUARIO_IDX ON FIDE_CUENTAS_AHORRO_TB(ID_USUARIO);

-- Indice FIDE_MOVIMIENTOS_AHORRO_IDX
CREATE INDEX FIDE_MOVIMIENTOS_AHORRO_IDX ON FIDE_MOVIMIENTOS_AHORRO_TB(ID_AHORRO);

-- Indice FIDE_PRESTAMO_USUARIO_IDX
CREATE INDEX FIDE_PRESTAMO_USUARIO_IDX ON FIDE_PRESTAMO_TB(ID_USUARIO);

-- Indice FIDE_PAGOS_PRESTAMOS_IDX
CREATE INDEX FIDE_PAGOS_PRESTAMOS_IDX ON FIDE_PAGOS_PRESTAMOS_TB(ID_PRESTAMO);

-- Indice FIDE_USUARIO_ROL_IDX
CREATE INDEX FIDE_USUARIO_ROL_IDX ON FIDE_USUARIO_TB(ID_ROL);

-- Indice FIDE_USUARIO_CORREO_IDX
CREATE INDEX FIDE_USUARIO_CORREO_IDX ON FIDE_USUARIO_TB(ID_CORREO);

-- Indice FIDE_INSCRIPCIONES_ACTIVIDAD_IDX
CREATE INDEX FIDE_INSCRIPCIONES_ACTIVIDAD_IDX ON FIDE_INSCRIPCIONES_ACTIVIDAD_TB(ID_ACTIVIDAD);

-- Indice FIDE_INSCRIPCIONES_USUARIO_IDX
CREATE INDEX FIDE_INSCRIPCIONES_USUARIO_IDX ON FIDE_INSCRIPCIONES_ACTIVIDAD_TB(ID_USUARIO);

-- Indice FIDE_RESULTADOS_REPORTE_IDX
CREATE INDEX FIDE_RESULTADOS_REPORTE_IDX ON FIDE_RESULTADOS_REPORTE_TB(ID_REPORTE);