
-- Triggers para Auditoría --

-- TRIGGER FIDE_ESTADO_TB
CREATE OR REPLACE TRIGGER FIDE_ESTADO_INSERT_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_ESTADO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADO_UPDATE_TRG
BEFORE UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_ESTADO_UPDATE_TRG;
/

-- TRIGGER FIDE_ROL_TB
CREATE OR REPLACE TRIGGER FIDE_ROL_INSERT_TRG
BEFORE INSERT ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_ROL_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ROL_UPDATE_TRG
BEFORE UPDATE ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_ROL_UPDATE_TRG;
/

-- TRIGGER FIDE_DIRECCION_TB
CREATE OR REPLACE TRIGGER FIDE_DIRECCION_INSERT_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_DIRECCION_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_UPDATE_TRG
BEFORE UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_DIRECCION_UPDATE_TRG;
/

-- TRIGGER FIDE_NUMERO_TELEFONO_TB
CREATE OR REPLACE TRIGGER FIDE_NUMERO_TELEFONO_INSERT_TRG
BEFORE INSERT ON FIDE_NUMERO_TELEFONO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_NUMERO_TELEFONO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_NUMERO_TELEFONO_UPDATE_TRG
BEFORE UPDATE ON FIDE_NUMERO_TELEFONO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_NUMERO_TELEFONO_UPDATE_TRG;
/

-- TRIGGER FIDE_CORREO_ELECTRONICO_TB
CREATE OR REPLACE TRIGGER FIDE_CORREO_ELECTRONICO_INSERT_TRG
BEFORE INSERT ON FIDE_CORREO_ELECTRONICO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_CORREO_ELECTRONICO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CORREO_ELECTRONICO_UPDATE_TRG
BEFORE UPDATE ON FIDE_CORREO_ELECTRONICO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_CORREO_ELECTRONICO_UPDATE_TRG;
/

-- TRIGGER FIDE_PUESTO_EMPRESA_ASOCIADO_TB
CREATE OR REPLACE TRIGGER FIDE_PUESTO_EMPRESA_ASOCIADO_INSERT_TRG
BEFORE INSERT ON FIDE_PUESTO_EMPRESA_ASOCIADO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_PUESTO_EMPRESA_ASOCIADO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PUESTO_EMPRESA_ASOCIADO_UPDATE_TRG
BEFORE UPDATE ON FIDE_PUESTO_EMPRESA_ASOCIADO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_PUESTO_EMPRESA_ASOCIADO_UPDATE_TRG;
/

-- TRIGGER FIDE_CATEGORIA_TB
CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_INSERT_TRG
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_CATEGORIA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_UPDATE_TRG
BEFORE UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_CATEGORIA_UPDATE_TRG;
/

-- TRIGGER FIDE_TIPO_TRANSACCION_TB
CREATE OR REPLACE TRIGGER FIDE_TIPO_TRANSACCION_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_TRANSACCION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_TIPO_TRANSACCION_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_TRANSACCION_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_TRANSACCION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_TIPO_TRANSACCION_UPDATE_TRG;
/

-- TRIGGER FIDE_TIPO_AHORRO_TB
CREATE OR REPLACE TRIGGER FIDE_TIPO_AHORRO_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_AHORRO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_TIPO_AHORRO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_AHORRO_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_AHORRO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_TIPO_AHORRO_UPDATE_TRG;
/

-- TRIGGER FIDE_MODULO_TB
CREATE OR REPLACE TRIGGER FIDE_MODULO_INSERT_TRG
BEFORE INSERT ON FIDE_MODULO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_MODULO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MODULO_UPDATE_TRG
BEFORE UPDATE ON FIDE_MODULO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_MODULO_UPDATE_TRG;
/

-- TRIGGER FIDE_TIPO_REPORTE_TB
CREATE OR REPLACE TRIGGER FIDE_TIPO_REPORTE_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_REPORTE_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_TIPO_REPORTE_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_REPORTE_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_REPORTE_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_TIPO_REPORTE_UPDATE_TRG;
/

-- TRIGGER FIDE_DATOS_ASOCIADOS_TB
CREATE OR REPLACE TRIGGER FIDE_DATOS_ASOCIADOS_INSERT_TRG
BEFORE INSERT ON FIDE_DATOS_ASOCIADOS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
END FIDE_DATOS_ASOCIADOS_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DATOS_ASOCIADOS_UPDATE_TRG
BEFORE UPDATE ON FIDE_DATOS_ASOCIADOS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_DATOS_ASOCIADOS_UPDATE_TRG;
/

-- TRIGGER FIDE_USUARIO_TB
CREATE OR REPLACE TRIGGER FIDE_USUARIO_INSERT_TRG
BEFORE INSERT ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_USUARIO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_USUARIO_UPDATE_TRG;
/

-- TRIGGER FIDE_USUARIOS_ROLES_TB
CREATE OR REPLACE TRIGGER FIDE_USUARIOS_ROLES_INSERT_TRG
BEFORE INSERT ON FIDE_USUARIOS_ROLES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
END FIDE_USUARIOS_ROLES_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIOS_ROLES_UPDATE_TRG
BEFORE UPDATE ON FIDE_USUARIOS_ROLES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_USUARIOS_ROLES_UPDATE_TRG;
/

-- TRIGGER FIDE_BENEFICIO_TB
CREATE OR REPLACE TRIGGER FIDE_BENEFICIO_INSERT_TRG
BEFORE INSERT ON FIDE_BENEFICIO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_BENEFICIO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_BENEFICIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_BENEFICIO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_BENEFICIO_UPDATE_TRG;
/

-- TRIGGER FIDE_SERVICIO_TB
CREATE OR REPLACE TRIGGER FIDE_SERVICIO_INSERT_TRG
BEFORE INSERT ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_SERVICIO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SERVICIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_SERVICIO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_SERVICIO_UPDATE_TRG;
/

-- TRIGGER FIDE_TRANSACCION_TB
CREATE OR REPLACE TRIGGER FIDE_TRANSACCION_INSERT_TRG
BEFORE INSERT ON FIDE_TRANSACCION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_TRANSACCION_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TRANSACCION_UPDATE_TRG
BEFORE UPDATE ON FIDE_TRANSACCION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_TRANSACCION_UPDATE_TRG;
/

-- TRIGGER FIDE_DETALLE_TRANSACCION_TB
CREATE OR REPLACE TRIGGER FIDE_DETALLE_TRANSACCION_INSERT_TRG
BEFORE INSERT ON FIDE_DETALLE_TRANSACCION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
END FIDE_DETALLE_TRANSACCION_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLE_TRANSACCION_UPDATE_TRG
BEFORE UPDATE ON FIDE_DETALLE_TRANSACCION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_DETALLE_TRANSACCION_UPDATE_TRG;
/

-- TRIGGER FIDE_CUENTAS_AHORRO_TB
CREATE OR REPLACE TRIGGER FIDE_CUENTAS_AHORRO_INSERT_TRG
BEFORE INSERT ON FIDE_CUENTAS_AHORRO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_CUENTAS_AHORRO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CUENTAS_AHORRO_UPDATE_TRG
BEFORE UPDATE ON FIDE_CUENTAS_AHORRO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_CUENTAS_AHORRO_UPDATE_TRG;
/

-- TRIGGER FIDE_MOVIMIENTOS_AHORRO_TB
CREATE OR REPLACE TRIGGER FIDE_MOVIMIENTOS_AHORRO_INSERT_TRG
BEFORE INSERT ON FIDE_MOVIMIENTOS_AHORRO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
END FIDE_MOVIMIENTOS_AHORRO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MOVIMIENTOS_AHORRO_UPDATE_TRG
BEFORE UPDATE ON FIDE_MOVIMIENTOS_AHORRO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_MOVIMIENTOS_AHORRO_UPDATE_TRG;
/

-- TRIGGER FIDE_PRESTAMO_TB
CREATE OR REPLACE TRIGGER FIDE_PRESTAMO_INSERT_TRG
BEFORE INSERT ON FIDE_PRESTAMO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_PRESTAMO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PRESTAMO_UPDATE_TRG
BEFORE UPDATE ON FIDE_PRESTAMO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_PRESTAMO_UPDATE_TRG;
/

-- TRIGGER FIDE_PAGOS_PRESTAMOS_TB
CREATE OR REPLACE TRIGGER FIDE_PAGOS_PRESTAMOS_INSERT_TRG
BEFORE INSERT ON FIDE_PAGOS_PRESTAMOS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
END FIDE_PAGOS_PRESTAMOS_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PAGOS_PRESTAMOS_UPDATE_TRG
BEFORE UPDATE ON FIDE_PAGOS_PRESTAMOS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_PAGOS_PRESTAMOS_UPDATE_TRG;
/

-- TRIGGER FIDE_ACTIVIDAD_TB
CREATE OR REPLACE TRIGGER FIDE_ACTIVIDAD_INSERT_TRG
BEFORE INSERT ON FIDE_ACTIVIDAD_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_ACTIVIDAD_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ACTIVIDAD_UPDATE_TRG
BEFORE UPDATE ON FIDE_ACTIVIDAD_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_ACTIVIDAD_UPDATE_TRG;
/

-- TRIGGER FIDE_INSCRIPCIONES_ACTIVIDAD_TB
CREATE OR REPLACE TRIGGER FIDE_INSCRIPCIONES_ACTIVIDAD_INSERT_TRG
BEFORE INSERT ON FIDE_INSCRIPCIONES_ACTIVIDAD_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_INSCRIPCIONES_ACTIVIDAD_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_INSCRIPCIONES_ACTIVIDAD_UPDATE_TRG
BEFORE UPDATE ON FIDE_INSCRIPCIONES_ACTIVIDAD_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_INSCRIPCIONES_ACTIVIDAD_UPDATE_TRG;
/

-- TRIGGER FIDE_REPORTES_TB
CREATE OR REPLACE TRIGGER FIDE_REPORTES_INSERT_TRG
BEFORE INSERT ON FIDE_REPORTES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
:NEW.ID_ESTADO:= 1;
END FIDE_REPORTES_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_REPORTES_UPDATE_TRG
BEFORE UPDATE ON FIDE_REPORTES_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_REPORTES_UPDATE_TRG;
/

-- TRIGGER FIDE_RESULTADOS_REPORTE_TB
CREATE OR REPLACE TRIGGER FIDE_RESULTADOS_REPORTE_INSERT_TRG
BEFORE INSERT ON FIDE_RESULTADOS_REPORTE_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
:NEW.CREADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'INSERT';
END FIDE_RESULTADOS_REPORTE_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_RESULTADOS_REPORTE_UPDATE_TRG
BEFORE UPDATE ON FIDE_RESULTADOS_REPORTE_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
:NEW.MODIFICADO_POR:=SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION:= 'UPDATE';
END FIDE_RESULTADOS_REPORTE_UPDATE_TRG;
/