-- JOBS PARA VISTAS MATERIALIZADAS

-- JOB 1: Actualizar FIDE_TOP10_MENOS_AHORROS_VM cada 5 minutos
BEGIN
DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME => 'FIDE_ASEFIDE_REFRESH_TOP10_MENOS_AHORROS_JOB',
JOB_TYPE => 'PLSQL_BLOCK',
JOB_ACTION => 'BEGIN DBMS_MVIEW.REFRESH(''FIDE_TOP10_MENOS_AHORROS_VM'',''C''); END;',
START_DATE => SYSTIMESTAMP,
REPEAT_INTERVAL => 'FREQ=MINUTELY; INTERVAL=5',
ENABLED => TRUE
);
END;
/

-- JOB 2: Actualizar FIDE_USUARIOS_ULTIMO_MES_VM cada 1 hora
BEGIN
DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME => 'FIDE_ASEFIDE_REFRESH_ULTIMO_MES_JOB',
JOB_TYPE => 'PLSQL_BLOCK',
JOB_ACTION => 'BEGIN DBMS_MVIEW.REFRESH(''FIDE_USUARIOS_ULTIMO_MES_VM'',''C''); END;',
START_DATE => SYSTIMESTAMP,
REPEAT_INTERVAL => 'FREQ=HOURLY; INTERVAL=1',
ENABLED => TRUE
);
END;
/

-- JOB 3: Actualizar FIDE_TOP_USUARIOS_TRANSACCIONES_VM cada 5 minutos
BEGIN
DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME => 'FIDE_ASEFIDE_REFRESH_TOP5_TRANSACCIONES_JOB',
JOB_TYPE => 'PLSQL_BLOCK',
JOB_ACTION => 'BEGIN DBMS_MVIEW.REFRESH(''FIDE_TOP_USUARIOS_TRANSACCIONES_VM'',''C''); END;',
START_DATE => SYSTIMESTAMP,
REPEAT_INTERVAL => 'FREQ=MINUTELY; INTERVAL=5',
ENABLED => TRUE
);
END;
/

-- JOB 4: Actualizar FIDE_USUARIOS_MAYOR_AHORRO_VM cada 5 minutos
BEGIN
DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME => 'FIDE_ASEFIDE_REFRESH_MAYOR_AHORRO_JOB',
JOB_TYPE => 'PLSQL_BLOCK',
JOB_ACTION => 'BEGIN DBMS_MVIEW.REFRESH(''FIDE_USUARIOS_MAYOR_AHORRO_VM'',''C''); END;',
START_DATE => SYSTIMESTAMP,
REPEAT_INTERVAL => 'FREQ=MINUTELY; INTERVAL=5',
ENABLED => TRUE
);
END;
/

-- JOB 5: Actualizar FIDE_HISTORIAL_TRANSACCIONES_VM cada 10 minutos
BEGIN
DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME => 'FIDE_ASEFIDE_REFRESH_HISTORIAL_TRANS_JOB',
JOB_TYPE => 'PLSQL_BLOCK',
JOB_ACTION => 'BEGIN DBMS_MVIEW.REFRESH(''FIDE_HISTORIAL_TRANSACCIONES_VM'',''C''); END;',
START_DATE => SYSTIMESTAMP,
REPEAT_INTERVAL => 'FREQ=MINUTELY; INTERVAL=10',
ENABLED => TRUE
);
END;
/