CREATE OR REPLACE VIEW V_FIDE_ACTIVIDADES_ASOCIADOS AS
SELECT A.ID_ACTIVIDAD,
       A.NOMBRE AS ACTIVIDAD_NOMBRE,
       A.DESCRIPCION,
       A.FECHA_EVENTO, 
       A.CUPO_TOTAL, 
       U.NOMBRE AS ENCARGADO_NOMBRE, 
       U.APELLIDO_PATERNO,        
       L.NOMBRE_LUGAR,
       A.IMAGEN_URL
FROM FIDE_ACTIVIDAD_TB A
LEFT JOIN FIDE_USUARIO_TB U ON A.ID_USUARIO = U.ID_USUARIO
LEFT JOIN FIDE_LUGAR_EVENTO_TB L ON A.ID_LUGAR_EVENTO = L.ID_LUGAR_EVENTO;
/


CREATE OR REPLACE VIEW V_FIDE_ACTIVIDADES_CON_INSCRITOS AS
SELECT 
    A.NOMBRE AS NOMBRE_ACTIVIDAD,
    A.FECHA_EVENTO,
    L.NOMBRE_LUGAR,
    COUNT(I.ID_INSCRIPCION) AS TOTAL_INSCRITOS,
    (A.CUPO_TOTAL - COUNT(I.ID_INSCRIPCION)) AS CUPO_DISPONIBLE
FROM FIDE_ACTIVIDAD_TB A
LEFT JOIN FIDE_INSCRIPCIONES_ACTIVIDAD_TB I ON A.ID_ACTIVIDAD = I.ID_ACTIVIDAD
INNER JOIN FIDE_LUGAR_EVENTO_TB L ON A.ID_LUGAR_EVENTO = L.ID_LUGAR_EVENTO
GROUP BY A.ID_ACTIVIDAD, A.NOMBRE, A.FECHA_EVENTO, L.NOMBRE_LUGAR, A.CUPO_TOTAL
/

CREATE OR REPLACE VIEW V_FIDE_ACTIVIDADES_PROGRAMADAS AS
SELECT AC.ID_ACTIVIDAD,
       AC.NOMBRE AS NOMBRE_ACTIVIDAD,
       AC.FECHA_EVENTO,
       AC.ID_LUGAR_EVENTO,
       AC.CUPO_TOTAL,
       U.NOMBRE || ' ' || U.APELLIDO_PATERNO AS NOMBRE_COMPLETO_RESPONSABLE,
       E.NOMBRE AS ESTADO_ACTIVIDAD
FROM FIDE_ACTIVIDAD_TB AC
JOIN FIDE_ESTADO_TB E ON AC.ID_ESTADO = E.ID_ESTADO
JOIN FIDE_USUARIO_TB U ON AC.ID_USUARIO = U.ID_USUARIO
/

CREATE OR REPLACE VIEW V_FIDE_AHORROS_POR_TIPO_ESTADO AS
SELECT 
    TA.NOMBRE AS TIPO_AHORRO,
    E.NOMBRE AS ESTADO,
    COUNT(A.ID_AHORRO) AS CANTIDAD_CUENTAS,
    SUM(A.SALDO_ACTUAL) AS SALDO_TOTAL,
    (SUM(A.SALDO_ACTUAL) / NULLIF(COUNT(A.ID_AHORRO), 0)) AS PROMEDIO_SALDO
FROM FIDE_CUENTAS_AHORRO_TB A
JOIN FIDE_TIPO_AHORRO_TB TA ON A.ID_TIPO_AHORRO = TA.ID_TIPO_AHORRO
JOIN FIDE_ESTADO_TB E ON A.ID_ESTADO = E.ID_ESTADO
GROUP BY TA.NOMBRE, E.NOMBRE
/

CREATE OR REPLACE VIEW V_FIDE_AHORROS_USUARIO AS
SELECT 
    U.ID_USUARIO,
    
    U.NOMBRE || ' ' || U.APELLIDO_PATERNO || ' ' || U.APELLIDO_MATERNO 
        AS NOMBRE_COMPLETO,
        
    U.NOMBRE_USUARIO,
    
    CA.ID_AHORRO,
    CA.FECHA_APERTURA,
    CA.MONTO_APORTE,
    CA.SALDO_ACTUAL,
    
    TA.NOMBRE AS TIPO_AHORRO,
    
    E.NOMBRE AS ESTADO_CUENTA

FROM FIDE_USUARIO_TB U
JOIN FIDE_CUENTAS_AHORRO_TB CA ON U.ID_USUARIO = CA.ID_USUARIO
JOIN FIDE_TIPO_AHORRO_TB TA ON CA.ID_TIPO_AHORRO = TA.ID_TIPO_AHORRO
JOIN FIDE_ESTADO_TB E ON CA.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_FIDE_APORTES_USUARIO AS
SELECT 
    U.ID_USUARIO,
    DA.ID_DATOS_ASOCIADOS, 
    U.NOMBRE || ' ' || U.APELLIDO_PATERNO || ' ' || U.APELLIDO_MATERNO AS NOMBRE_COMPLETO,
    U.NOMBRE_USUARIO,

    COUNT(A.ID_APORTE) AS CANTIDAD_APORTES,
    NVL(SUM(A.MONTO), 0) AS TOTAL_APORTES,

    MAX(A.MONTO) KEEP (DENSE_RANK LAST ORDER BY A.FECHA_INICIO) AS APORTE_VIGENTE,

    PE.PUESTO_EMPRESA,
    DA.FECHA_AFILIACION,
    E.NOMBRE AS ESTADO_USUARIO

FROM FIDE_DATOS_ASOCIADOS_TB DA

LEFT JOIN FIDE_USUARIO_TB U 
    ON U.ID_DATOS_ASOCIADOS = DA.ID_DATOS_ASOCIADOS

JOIN FIDE_PUESTO_EMPRESA_ASOCIADO_TB PE 
    ON DA.ID_PUESTO_EMPRESA = PE.ID_PUESTO_EMPRESA

LEFT JOIN FIDE_ESTADO_TB E 
    ON U.ID_ESTADO = E.ID_ESTADO

LEFT JOIN FIDE_APORTE_TB A 
    ON DA.ID_DATOS_ASOCIADOS = A.ID_DATOS_ASOCIADOS

GROUP BY 
    U.ID_USUARIO,
    U.NOMBRE,
    U.APELLIDO_PATERNO,
    U.APELLIDO_MATERNO,
    U.NOMBRE_USUARIO,
    DA.ID_DATOS_ASOCIADOS,
    DA.FECHA_AFILIACION,
    PE.PUESTO_EMPRESA,
    E.NOMBRE
/


CREATE OR REPLACE VIEW V_FIDE_ASOCIADOS_NUEVOS_MES AS
SELECT 
    U.NOMBRE || ' ' || U.APELLIDO_PATERNO || ' ' || NVL(U.APELLIDO_MATERNO, '') AS NOMBRE_COMPLETO,
    DA.FECHA_AFILIACION,
    E.NOMBRE AS ESTADO,
    DA.APORTE_MENSUAL
FROM FIDE_USUARIO_TB U
JOIN FIDE_DATOS_ASOCIADOS_TB DA ON U.ID_DATOS_ASOCIADOS = DA.ID_DATOS_ASOCIADOS
JOIN FIDE_ESTADO_TB E ON U.ID_ESTADO = E.ID_ESTADO
WHERE TO_CHAR(DA.FECHA_AFILIACION, 'YYYY-MM') = TO_CHAR(SYSDATE, 'YYYY-MM')
/

CREATE OR REPLACE VIEW V_FIDE_BENEFICIOS_ASOCIADOS AS
SELECT 
    ID_BENEFICIO,
    NOMBRE_BENEFICIO,
    DESCRIPCION,
    IMAGEN_URL
FROM FIDE_BENEFICIO_TB
/


CREATE OR REPLACE VIEW V_BENEFICIOS_DETALLE AS
SELECT 
    B.NOMBRE_BENEFICIO,
    B.DESCRIPCION,
    C.NOMBRE AS CATEGORIA,
    E.NOMBRE AS VIGENCIA
FROM FIDE_BENEFICIO_TB B
JOIN FIDE_CATEGORIA_TB C ON B.ID_CATEGORIA = C.ID_CATEGORIA
JOIN FIDE_ESTADO_TB E ON B.ID_ESTADO = E.ID_ESTADO
/

CREATE OR REPLACE VIEW V_FIDE_DASHBOARD_ACTIVIDADES_PROXIMAS AS
WITH ESTADO_ACTIVO AS (
    SELECT ID_ESTADO
    FROM FIDE_ESTADO_TB
    WHERE UPPER(NOMBRE) = 'ACTIVO'
    AND ROWNUM = 1
)
SELECT
    a.ID_ACTIVIDAD,
    a.NOMBRE                                 AS NOMBRE_ACTIVIDAD,
    a.FECHA_EVENTO,
    a.CUPO_TOTAL,
    l.NOMBRE_LUGAR                                 AS LUGAR,  -- nombre del lugar
    COUNT(ia.ID_INSCRIPCION)                 AS TOTAL_INSCRITOS,
    a.CUPO_TOTAL - COUNT(ia.ID_INSCRIPCION) AS CUPO_DISPONIBLE,
    ROUND(
        COUNT(ia.ID_INSCRIPCION) * 100.0
        / NULLIF(a.CUPO_TOTAL, 0),
        2
    )                                        AS PORCENTAJE_OCUPACION,
    (a.FECHA_EVENTO - TRUNC(SYSDATE))        AS DIAS_PARA_EVENTO
FROM FIDE_ACTIVIDAD_TB a
CROSS JOIN ESTADO_ACTIVO ea
LEFT JOIN FIDE_INSCRIPCIONES_ACTIVIDAD_TB ia
    ON a.ID_ACTIVIDAD = ia.ID_ACTIVIDAD
    AND ia.ID_ESTADO = ea.ID_ESTADO
LEFT JOIN FIDE_LUGAR_EVENTO_TB l
    ON a.ID_LUGAR_EVENTO = l.ID_LUGAR_EVENTO
WHERE a.FECHA_EVENTO >= TRUNC(SYSDATE)
  AND a.ID_ESTADO = ea.ID_ESTADO
GROUP BY
    a.ID_ACTIVIDAD,
    a.NOMBRE,
    a.FECHA_EVENTO,
    a.CUPO_TOTAL,
    l.NOMBRE_LUGAR
ORDER BY
    a.FECHA_EVENTO ASC
FETCH FIRST 5 ROWS ONLY
/


CREATE OR REPLACE VIEW V_FIDE_DASHBOARD_KPIS AS
SELECT
    (SELECT COUNT(*) FROM FIDE_USUARIO_TB u
     JOIN FIDE_ESTADO_TB e ON u.ID_ESTADO = e.ID_ESTADO
     WHERE UPPER(e.NOMBRE) = 'ACTIVO') AS ASOCIADOS_ACTIVOS,

    (SELECT NVL(SUM(SALDO_ACTUAL), 0)
     FROM FIDE_CUENTAS_AHORRO_TB) AS SALDO_TOTAL_AHORROS,

    (SELECT COUNT(*) FROM FIDE_PRESTAMO_TB p
     JOIN FIDE_ESTADO_TB e ON p.ID_ESTADO = e.ID_ESTADO
     WHERE UPPER(e.NOMBRE) != 'Completado') AS PRESTAMOS_PENDIENTES,

    (SELECT COUNT(*) FROM FIDE_TRANSACCION_TB
     WHERE TRUNC(FECHA_TRANSACCION, 'MM') = TRUNC(SYSDATE, 'MM')) AS TRANSACCIONES_MES
FROM DUAL
/


CREATE OR REPLACE VIEW V_DASHBOARD_PRESTAMOS_ESTADO AS
SELECT
    e.NOMBRE                          AS ESTADO,
    COUNT(p.ID_PRESTAMO)              AS TOTAL_PRESTAMOS,
    NVL(SUM(p.SALDO_PENDIENTE), 0)    AS SALDO_PENDIENTE_TOTAL,
    NVL(AVG(p.SALDO_PENDIENTE), 0)    AS SALDO_PROMEDIO,
    NVL(SUM(p.MONTO_SOLICITADO), 0)   AS MONTO_SOLICITADO_TOTAL,
    ROUND(
        COUNT(p.ID_PRESTAMO) * 100.0
        / NULLIF(SUM(COUNT(p.ID_PRESTAMO)) OVER (), 0),
        2
    )                                 AS PORCENTAJE_PRESTAMOS
FROM FIDE_ESTADO_TB e
LEFT JOIN FIDE_PRESTAMO_TB p
    ON e.ID_ESTADO = p.ID_ESTADO
WHERE e.ID_ESTADO IN (
    SELECT DISTINCT ID_ESTADO
    FROM FIDE_PRESTAMO_TB
)
GROUP BY
    e.ID_ESTADO,
    e.NOMBRE
ORDER BY
    SALDO_PENDIENTE_TOTAL DESC
/


CREATE OR REPLACE VIEW V_FIDE_ESTADO_PRESTAMOS AS
SELECT P.ID_PRESTAMO,
       U.NOMBRE || ' ' || U.APELLIDO_PATERNO AS CLIENTE,
       P.MONTO_SOLICITADO,
       P.SALDO_PENDIENTE,
       P.TASA_INTERESES,
       P.PLAZO_MESES,
       P.FECHA_APROBACION,
       E.NOMBRE AS ESTADO_PRESTAMO
FROM FIDE_PRESTAMO_TB P
JOIN FIDE_USUARIO_TB U ON P.ID_USUARIO = U.ID_USUARIO
JOIN FIDE_ESTADO_TB E ON P.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_FIDE_HISTORIAL_APORTES AS
SELECT 
    U.NOMBRE_USUARIO,
    TO_NUMBER(TO_CHAR(T.FECHA_TRANSACCION, 'MM')) AS MES,
    TO_NUMBER(TO_CHAR(T.FECHA_TRANSACCION, 'YYYY')) AS ANIO,
    DT.SUB_TOTAL AS MONTO_APORTE,
    E.NOMBRE AS ESTADO_PAGO
FROM FIDE_TRANSACCION_TB T
JOIN FIDE_USUARIO_TB U ON T.ID_USUARIO = U.ID_USUARIO
JOIN FIDE_ESTADO_TB E ON T.ID_ESTADO = E.ID_ESTADO
JOIN FIDE_DETALLE_TRANSACCION_TB DT ON T.ID_TRANSACCION = DT.ID_TRANSACCION
WHERE UPPER(DT.CONCEPTO) LIKE '%APORTE%'
/


CREATE OR REPLACE VIEW V_FIDE_MIS_INSCRIPCIONES AS
SELECT 
    U.NOMBRE_USUARIO,
    A.NOMBRE AS NOMBRE_ACTIVIDAD,
    A.FECHA_EVENTO,
    L.NOMBRE_LUGAR,
    E.NOMBRE AS ESTADO_INSCRIPCION
FROM FIDE_INSCRIPCIONES_ACTIVIDAD_TB I
JOIN FIDE_USUARIO_TB U ON I.ID_USUARIO = U.ID_USUARIO
JOIN FIDE_ACTIVIDAD_TB A ON I.ID_ACTIVIDAD = A.ID_ACTIVIDAD
JOIN FIDE_LUGAR_EVENTO_TB L ON A.ID_LUGAR_EVENTO = L.ID_LUGAR_EVENTO
JOIN FIDE_ESTADO_TB E ON I.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_FIDE_MIS_PRESTAMOS AS
SELECT 
    U.NOMBRE_USUARIO,
    P.MONTO_SOLICITADO,
    P.SALDO_PENDIENTE,
    (SELECT COUNT(PP.ID_PAGO) FROM FIDE_PAGOS_PRESTAMOS_TB PP WHERE PP.ID_PRESTAMO = P.ID_PRESTAMO) AS CUOTAS_PAGADAS,
    (P.PLAZO_MESES - (SELECT COUNT(PP.ID_PAGO) FROM FIDE_PAGOS_PRESTAMOS_TB PP WHERE PP.ID_PRESTAMO = P.ID_PRESTAMO)) AS CUOTAS_PENDIENTES,
    ADD_MONTHS(P.FECHA_APROBACION, (SELECT COUNT(PP.ID_PAGO) FROM FIDE_PAGOS_PRESTAMOS_TB PP WHERE PP.ID_PRESTAMO = P.ID_PRESTAMO) + 1) AS PROXIMA_FECHA_PAGO,
    E.NOMBRE AS ESTADO
FROM FIDE_PRESTAMO_TB P
JOIN FIDE_USUARIO_TB U ON P.ID_USUARIO = U.ID_USUARIO
JOIN FIDE_ESTADO_TB E ON P.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_FIDE_MIS_TRANSACCIONES AS
SELECT 
    U.NOMBRE_USUARIO,
    TT.NOMBRE AS TIPO_TRANSACCION,
    T.MONTO_TOTAL AS MONTO,
    T.FECHA_TRANSACCION,
    DT.CONCEPTO AS DESCRIPCION
FROM FIDE_TRANSACCION_TB T
JOIN FIDE_USUARIO_TB U ON T.ID_USUARIO = U.ID_USUARIO
JOIN FIDE_TIPO_TRANSACCION_TB TT ON T.ID_TIPO_TRANSACCION = TT.ID_TIPO_TRANSACCION
LEFT JOIN FIDE_DETALLE_TRANSACCION_TB DT ON T.ID_TRANSACCION = DT.ID_TRANSACCION
ORDER BY T.FECHA_TRANSACCION DESC
/


CREATE OR REPLACE VIEW V_FIDE_MIS_PRESTAMOS_DETALLE AS
SELECT 
    U.NOMBRE || ' ' || U.APELLIDO_PATERNO || ' ' || NVL(U.APELLIDO_MATERNO, '') AS NOMBRE_ASOCIADO,
    P.MONTO_SOLICITADO,
    P.SALDO_PENDIENTE,
    (SELECT COUNT(PP.ID_PAGO) FROM FIDE_PAGOS_PRESTAMOS_TB PP WHERE PP.ID_PRESTAMO = P.ID_PRESTAMO) AS CUOTAS_PAGADAS,
    (P.PLAZO_MESES - (SELECT COUNT(PP.ID_PAGO) FROM FIDE_PAGOS_PRESTAMOS_TB PP WHERE PP.ID_PRESTAMO = P.ID_PRESTAMO)) AS CUOTAS_PENDIENTES,
    ADD_MONTHS(P.FECHA_APROBACION, P.PLAZO_MESES) AS FECHA_VENCIMIENTO,
    P.TASA_INTERESES AS TASA_INTERES,
    E.NOMBRE AS ESTADO
FROM FIDE_PRESTAMO_TB P
JOIN FIDE_USUARIO_TB U ON P.ID_USUARIO = U.ID_USUARIO
JOIN FIDE_ESTADO_TB E ON P.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_FIDE_RESUMEN_AHORROS AS
SELECT A.ID_AHORRO,
       U.NOMBRE_USUARIO,
       TA.NOMBRE AS TIPO_AHORRO,
       A.MONTO_APORTE,
       A.SALDO_ACTUAL,
       A.FECHA_APERTURA,
       E.NOMBRE AS ESTADO_CUENTA
FROM FIDE_CUENTAS_AHORRO_TB A
JOIN FIDE_USUARIO_TB U ON A.ID_USUARIO = U.ID_USUARIO
JOIN FIDE_TIPO_AHORRO_TB TA ON A.ID_TIPO_AHORRO = TA.ID_TIPO_AHORRO
JOIN FIDE_ESTADO_TB E ON A.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_FIDE_RESUMEN_ESTADOS AS
SELECT 
    E.NOMBRE AS ESTADO,
    (SELECT COUNT(U.ID_USUARIO) FROM FIDE_USUARIO_TB U WHERE U.ID_ESTADO = E.ID_ESTADO) AS TOTAL_USUARIOS,
    (SELECT COUNT(P.ID_PRESTAMO) FROM FIDE_PRESTAMO_TB P WHERE P.ID_ESTADO = E.ID_ESTADO) AS TOTAL_PRESTAMOS,
    (SELECT COUNT(A.ID_AHORRO) FROM FIDE_CUENTAS_AHORRO_TB A WHERE A.ID_ESTADO = E.ID_ESTADO) AS TOTAL_CUENTAS_AHORRO,
    (SELECT COUNT(AC.ID_ACTIVIDAD) FROM FIDE_ACTIVIDAD_TB AC WHERE AC.ID_ESTADO = E.ID_ESTADO) AS TOTAL_ACTIVIDADES
FROM FIDE_ESTADO_TB E
/


CREATE OR REPLACE VIEW V_FIDE_SERVICIOS_ASOCIADOS AS
SELECT
    ID_SERVICIO,
    NOMBRE_SERVICIO,
    DESCRIPCION,
    VALOR_ESTIMADO,
    STOCK,
    IMAGEN_URL
FROM FIDE_SERVICIO_TB
/


CREATE OR REPLACE VIEW V_FIDE_SERVICIOS_MAS_SOLICITADOS AS
SELECT 
    S.NOMBRE_SERVICIO,
    0 AS TOTAL_SOLICITUDES,
    S.STOCK AS STOCK_DISPONIBLE,
    S.VALOR_ESTIMADO
FROM FIDE_SERVICIO_TB S
ORDER BY S.STOCK ASC
/

CREATE OR REPLACE VIEW V_FIDE_TOP10_MAS_AHORROS AS
SELECT "NOMBRE_COMPLETO","TOTAL_AHORRO","CANTIDAD_CUENTAS" FROM (
    SELECT 
        U.NOMBRE || ' ' || U.APELLIDO_PATERNO || ' ' || NVL(U.APELLIDO_MATERNO, '') AS NOMBRE_COMPLETO,
        SUM(A.SALDO_ACTUAL) AS TOTAL_AHORRO,
        COUNT(A.ID_AHORRO) AS CANTIDAD_CUENTAS
    FROM FIDE_USUARIO_TB U
    JOIN FIDE_CUENTAS_AHORRO_TB A ON U.ID_USUARIO = A.ID_USUARIO
    GROUP BY U.ID_USUARIO, U.NOMBRE, U.APELLIDO_PATERNO, U.APELLIDO_MATERNO
    ORDER BY TOTAL_AHORRO DESC
)
WHERE ROWNUM <= 10
/


CREATE OR REPLACE VIEW V_FIDE_TOP5_TRANSACCIONES AS
SELECT "NOMBRE_COMPLETO","TOTAL_TRANSACCIONES","MONTO_TOTAL" FROM (
    SELECT 
        U.NOMBRE || ' ' || U.APELLIDO_PATERNO || ' ' || NVL(U.APELLIDO_MATERNO, '') AS NOMBRE_COMPLETO,
        COUNT(T.ID_TRANSACCION) AS TOTAL_TRANSACCIONES,
        SUM(T.MONTO_TOTAL) AS MONTO_TOTAL
    FROM FIDE_USUARIO_TB U
    JOIN FIDE_TRANSACCION_TB T ON U.ID_USUARIO = T.ID_USUARIO
    GROUP BY U.ID_USUARIO, U.NOMBRE, U.APELLIDO_PATERNO, U.APELLIDO_MATERNO
    ORDER BY TOTAL_TRANSACCIONES DESC
)
WHERE ROWNUM <= 5
/

CREATE OR REPLACE VIEW V_FIDE_TRANSACCIONES_RECIENTES AS
SELECT "NOMBRE_USUARIO","TIPO_TRANSACCION","MONTO","FECHA_TRANSACCION","DESCRIPCION" FROM (
    SELECT 
        U.NOMBRE_USUARIO,
        TT.NOMBRE AS TIPO_TRANSACCION,
        T.MONTO_TOTAL AS MONTO,
        T.FECHA_TRANSACCION,
        DT.CONCEPTO AS DESCRIPCION
    FROM FIDE_TRANSACCION_TB T
    JOIN FIDE_USUARIO_TB U ON T.ID_USUARIO = U.ID_USUARIO
    JOIN FIDE_TIPO_TRANSACCION_TB TT ON T.ID_TIPO_TRANSACCION = TT.ID_TIPO_TRANSACCION
    LEFT JOIN FIDE_DETALLE_TRANSACCION_TB DT ON T.ID_TRANSACCION = DT.ID_TRANSACCION
    ORDER BY T.FECHA_TRANSACCION DESC
)
WHERE ROWNUM <= 20
/

CREATE OR REPLACE VIEW V_FIDE_USUARIOS_COMPLETOS AS
SELECT U.ID_USUARIO,
       U.IDENTIFICACION,
       U.NOMBRE,
       U.APELLIDO_PATERNO,
       U.APELLIDO_MATERNO,
       U.NOMBRE_USUARIO,
       E.NOMBRE AS ESTADO_USUARIO,
       D.FECHA_AFILIACION
FROM FIDE_USUARIO_TB U
JOIN FIDE_ESTADO_TB E ON U.ID_ESTADO = E.ID_ESTADO
LEFT JOIN FIDE_DATOS_ASOCIADOS_TB D ON U.ID_DATOS_ASOCIADOS = D.ID_DATOS_ASOCIADOS
/

CREATE OR REPLACE VIEW V_FIDE_USUARIOS_INACTIVOS AS
SELECT U.ID_USUARIO,
       U.NOMBRE || ' ' || U.APELLIDO_PATERNO AS NOMBRE,
       E.NOMBRE AS ESTADO
FROM FIDE_USUARIO_TB U
JOIN FIDE_ESTADO_TB E ON U.ID_ESTADO = E.ID_ESTADO
WHERE U.ID_ESTADO = 2
/

CREATE OR REPLACE VIEW V_FIDE_USUARIOS_ULTIMO_MES AS
SELECT 
    U.NOMBRE || ' ' || U.APELLIDO_PATERNO || ' ' || NVL(U.APELLIDO_MATERNO, '') AS NOMBRE_COMPLETO,
    DA.FECHA_AFILIACION,
    E.NOMBRE AS ESTADO
FROM FIDE_USUARIO_TB U
JOIN FIDE_DATOS_ASOCIADOS_TB DA ON U.ID_DATOS_ASOCIADOS = DA.ID_DATOS_ASOCIADOS
JOIN FIDE_ESTADO_TB E ON U.ID_ESTADO = E.ID_ESTADO
WHERE DA.FECHA_AFILIACION >= ADD_MONTHS(SYSDATE, -1)
/

CREATE OR REPLACE VIEW V_LISTAR_FIDE_ACTIVIDAD_TB AS
SELECT A.ID_ACTIVIDAD,
       A.NOMBRE,
       A.DESCRIPCION,
       A.FECHA_EVENTO,
       L.NOMBRE_LUGAR,
       A.CUPO_TOTAL,
       E.NOMBRE AS ESTADO,
       U.NOMBRE_USUARIO AS CREADOR_EVENTO,
       A.FECHA_CREACION,
       A.FECHA_MODIFICACION,
       A.CREADO_POR,
       A.MODIFICADO_POR,
       A.ACCION
FROM FIDE_ACTIVIDAD_TB A
LEFT JOIN FIDE_ESTADO_TB E ON A.ID_ESTADO = E.ID_ESTADO
LEFT JOIN FIDE_USUARIO_TB U ON A.ID_USUARIO = U.ID_USUARIO
LEFT JOIN FIDE_LUGAR_EVENTO_TB L ON A.ID_LUGAR_EVENTO = L.ID_LUGAR_EVENTO
/

CREATE OR REPLACE VIEW V_LISTAR_FIDE_BENEFICIO_TB AS
SELECT B.ID_BENEFICIO,
       B.NOMBRE_BENEFICIO,
       B.DESCRIPCION,
       B.IMAGEN_URL,
       C.NOMBRE AS CATEGORIA,
       E.NOMBRE AS ESTADO,
       B.FECHA_CREACION,
       B.FECHA_MODIFICACION,
       B.CREADO_POR,
       B.MODIFICADO_POR,
       B.ACCION
FROM FIDE_BENEFICIO_TB B
LEFT JOIN FIDE_CATEGORIA_TB C ON B.ID_CATEGORIA = C.ID_CATEGORIA
LEFT JOIN FIDE_ESTADO_TB E ON B.ID_ESTADO = E.ID_ESTADO
/

CREATE OR REPLACE VIEW V_LISTAR_FIDE_CATEGORIA_TB AS
SELECT C.ID_CATEGORIA,
       C.NOMBRE,
       C.DESCRIPCION,
       E.NOMBRE AS ESTADO,
       C.FECHA_CREACION,
       C.FECHA_MODIFICACION,
       C.CREADO_POR,
       C.MODIFICADO_POR,
       C.ACCION
FROM FIDE_CATEGORIA_TB C
LEFT JOIN FIDE_ESTADO_TB E ON C.ID_ESTADO = E.ID_ESTADO
/

CREATE OR REPLACE VIEW V_LISTAR_FIDE_CORREO_ELECTRONICO_TB AS
SELECT C.ID_CORREO,
       C.CORREO_ELECTRONICO,
       E.NOMBRE AS ESTADO,
       C.FECHA_CREACION,
       C.FECHA_MODIFICACION,
       C.CREADO_POR,
       C.MODIFICADO_POR,
       C.ACCION
FROM FIDE_CORREO_ELECTRONICO_TB C
LEFT JOIN FIDE_ESTADO_TB E ON C.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_CUENTAS_AHORRO_TB AS
SELECT A.ID_AHORRO,
       A.ID_USUARIO, 
       U.NOMBRE_USUARIO,
       A.MONTO_APORTE,
       A.FECHA_APERTURA,
       TA.NOMBRE AS TIPO_AHORRO,
       A.SALDO_ACTUAL,
       E.NOMBRE AS ESTADO,
       A.FECHA_CREACION,
       A.FECHA_MODIFICACION,
       A.CREADO_POR,
       A.MODIFICADO_POR,
       A.ACCION
FROM FIDE_CUENTAS_AHORRO_TB A
LEFT JOIN FIDE_USUARIO_TB U ON A.ID_USUARIO = U.ID_USUARIO
LEFT JOIN FIDE_TIPO_AHORRO_TB TA ON A.ID_TIPO_AHORRO = TA.ID_TIPO_AHORRO
LEFT JOIN FIDE_ESTADO_TB E ON A.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_DATOS_ASOCIADOS_TB AS
SELECT D.ID_DATOS_ASOCIADOS,
       P.PUESTO_EMPRESA,
       D.FECHA_AFILIACION,
       D.APORTE_MENSUAL,
       D.FECHA_CREACION,
       D.FECHA_MODIFICACION,
       D.CREADO_POR,
       D.MODIFICADO_POR,
       D.ACCION
FROM FIDE_DATOS_ASOCIADOS_TB D
LEFT JOIN FIDE_PUESTO_EMPRESA_ASOCIADO_TB P ON D.ID_PUESTO_EMPRESA = P.ID_PUESTO_EMPRESA
/

CREATE OR REPLACE VIEW V_LISTAR_FIDE_DETALLE_TRANSACCION_TB AS
SELECT DT.ID_DETALLE,
       DT.ID_TRANSACCION,
       T.FECHA_TRANSACCION,
       DT.CONCEPTO,
       DT.SUB_TOTAL,
       DT.FECHA_CREACION,
       DT.FECHA_MODIFICACION,
       DT.CREADO_POR,
       DT.MODIFICADO_POR,
       DT.ACCION
FROM FIDE_DETALLE_TRANSACCION_TB DT
LEFT JOIN FIDE_TRANSACCION_TB T ON DT.ID_TRANSACCION = T.ID_TRANSACCION
/

CREATE OR REPLACE VIEW V_LISTAR_FIDE_DIRECCION_TB AS 
SELECT D.ID_DIRECCION,
       D.PROVINCIA,
       D.CANTON,
       D.DISTRITO,
       E.NOMBRE AS ESTADO,
       D.FECHA_CREACION,
       D.FECHA_MODIFICACION,
       D.CREADO_POR,
       D.MODIFICADO_POR,
       D.ACCION
FROM FIDE_DIRECCION_TB D
LEFT JOIN FIDE_ESTADO_TB E ON D.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_ESTADO_TB AS
SELECT ID_ESTADO,
       NOMBRE,
       FECHA_CREACION,
       FECHA_MODIFICACION,
       CREADO_POR,
       MODIFICADO_POR,
       ACCION
FROM FIDE_ESTADO_TB
/

CREATE OR REPLACE VIEW V_LISTAR_FIDE_INSCRIPCIONES_ACTIVIDAD_TB AS
SELECT I.ID_INSCRIPCION,
       A.NOMBRE AS ACTIVIDAD,
       U.NOMBRE_USUARIO,
       I.FECHA_INSCRIPCION,
       I.ASISTENCIA_CONFIRMADA,
       E.NOMBRE AS ESTADO,
       I.FECHA_CREACION,
       I.FECHA_MODIFICACION,
       I.CREADO_POR,
       I.MODIFICADO_POR,
       I.ACCION
FROM FIDE_INSCRIPCIONES_ACTIVIDAD_TB I
LEFT JOIN FIDE_ACTIVIDAD_TB A ON I.ID_ACTIVIDAD = A.ID_ACTIVIDAD
LEFT JOIN FIDE_USUARIO_TB U ON I.ID_USUARIO = U.ID_USUARIO
LEFT JOIN FIDE_ESTADO_TB E ON I.ID_ESTADO = E.ID_ESTADO
/

CREATE OR REPLACE VIEW V_LISTAR_FIDE_LUGAR_EVENTO_TB AS
SELECT L.ID_LUGAR_EVENTO,
       L.NOMBRE_LUGAR,
       E.NOMBRE AS ESTADO,
       L.FECHA_CREACION,
       L.FECHA_MODIFICACION,
       L.CREADO_POR,
       L.MODIFICADO_POR,
       L.ACCION
FROM FIDE_LUGAR_EVENTO_TB L
LEFT JOIN FIDE_ESTADO_TB E ON L.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_MODULO_TB AS
SELECT M.ID_MODULO,
       M.NOMBRE,
       M.DESCRIPCION,
       E.NOMBRE AS ESTADO,
       M.FECHA_CREACION,
       M.FECHA_MODIFICACION,
       M.CREADO_POR,
       M.MODIFICADO_POR,
       M.ACCION
FROM FIDE_MODULO_TB M
LEFT JOIN FIDE_ESTADO_TB E ON M.ID_ESTADO = E.ID_ESTADO
/

CREATE OR REPLACE VIEW V_LISTAR_FIDE_MOVIMIENTOS_AHORRO_TB AS
SELECT M.ID_MOVIMIENTO,
       A.ID_AHORRO,
       U.NOMBRE_USUARIO,
       M.ID_TRANSACCION,
       T.FECHA_TRANSACCION,
       M.MONTO,
       M.FECHA_DEPOSITO,
       M.FECHA_CREACION,
       M.FECHA_MODIFICACION,
       M.CREADO_POR,
       M.MODIFICADO_POR,
       M.ACCION
FROM FIDE_MOVIMIENTOS_AHORRO_TB M
LEFT JOIN FIDE_CUENTAS_AHORRO_TB A ON M.ID_AHORRO = A.ID_AHORRO
LEFT JOIN FIDE_USUARIO_TB U ON A.ID_USUARIO = U.ID_USUARIO
LEFT JOIN FIDE_TRANSACCION_TB T ON M.ID_TRANSACCION = T.ID_TRANSACCION
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_NUMERO_TELEFONO_TB AS
SELECT N.ID_NUMERO,
       N.NUMERO_TELEFONO,
       E.NOMBRE AS ESTADO,
       N.FECHA_CREACION,
       N.FECHA_MODIFICACION,
       N.CREADO_POR,
       N.MODIFICADO_POR,
       N.ACCION
FROM FIDE_NUMERO_TELEFONO_TB N
LEFT JOIN FIDE_ESTADO_TB E ON N.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_PAGOS_PRESTAMOS_TB AS
SELECT PP.ID_PAGO,
       PP.ID_TRANSACCION,
       T.FECHA_TRANSACCION,
       PP.ID_PRESTAMO,
       U.NOMBRE_USUARIO,
       PP.MONTO_ABONADO,
       PP.FECHA_PAGO,
       PP.FECHA_CREACION,
       PP.FECHA_MODIFICACION,
       PP.CREADO_POR,
       PP.MODIFICADO_POR,
       PP.ACCION
FROM FIDE_PAGOS_PRESTAMOS_TB PP
LEFT JOIN FIDE_TRANSACCION_TB T ON PP.ID_TRANSACCION = T.ID_TRANSACCION
LEFT JOIN FIDE_PRESTAMO_TB P ON PP.ID_PRESTAMO = P.ID_PRESTAMO
LEFT JOIN FIDE_USUARIO_TB U ON P.ID_USUARIO = U.ID_USUARIO
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_PRESTAMO_TB AS
SELECT P.ID_PRESTAMO,
       P.ID_USUARIO, 
       U.NOMBRE_USUARIO,
       P.MONTO_SOLICITADO,
       P.FECHA_APROBACION,
       P.SALDO_PENDIENTE,
       P.TASA_INTERESES,
       P.PLAZO_MESES,
       E.NOMBRE AS ESTADO,
       P.FECHA_CREACION,
       P.FECHA_MODIFICACION,
       P.CREADO_POR,
       P.MODIFICADO_POR,
       P.ACCION
FROM FIDE_PRESTAMO_TB P
LEFT JOIN FIDE_USUARIO_TB U ON P.ID_USUARIO = U.ID_USUARIO
LEFT JOIN FIDE_ESTADO_TB E ON P.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_LISTAR_PUESTO_EMPRESA_ASOCIADO_TB AS
SELECT P.ID_PUESTO_EMPRESA,
       P.PUESTO_EMPRESA,
       E.NOMBRE AS ESTADO,
       P.FECHA_CREACION,
       P.FECHA_MODIFICACION,
       P.CREADO_POR,
       P.MODIFICADO_POR,
       P.ACCION
FROM FIDE_PUESTO_EMPRESA_ASOCIADO_TB P
LEFT JOIN FIDE_ESTADO_TB E ON P.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_REPORTES_TB AS
SELECT R.ID_REPORTE,
       TR.NOMBRE AS TIPO_REPORTE,
       R.FECHA_INICIO,
       R.FECHA_FINAL,
       M.NOMBRE AS MODULO,
       R.TOTAL_REGISTROS,
       R.RESUMEN_MONTOS,
       R.FECHA_GENERACION,
       E.NOMBRE AS ESTADO,
       U.NOMBRE_USUARIO AS GENERADO_POR,
       R.FECHA_CREACION,
       R.FECHA_MODIFICACION,
       R.CREADO_POR,
       R.MODIFICADO_POR,
       R.ACCION
FROM FIDE_REPORTES_TB R
LEFT JOIN FIDE_TIPO_REPORTE_TB TR ON R.ID_TIPO_REPORTE = TR.ID_TIPO_REPORTE
LEFT JOIN FIDE_MODULO_TB M ON R.ID_MODULO = M.ID_MODULO
LEFT JOIN FIDE_ESTADO_TB E ON R.ID_ESTADO = E.ID_ESTADO
LEFT JOIN FIDE_USUARIO_TB U ON R.ID_USUARIO = U.ID_USUARIO
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_RESULTADOS_REPORTE_TB AS
SELECT RR.ID_RESULTADO,
       R.ID_REPORTE,
       TR.NOMBRE AS TIPO_REPORTE,
       RR.METRICA_NOMBRE,
       RR.METRICA_VALOR,
       RR.FECHA_CREACION,
       RR.FECHA_MODIFICACION,
       RR.CREADO_POR,
       RR.MODIFICADO_POR,
       RR.ACCION
FROM FIDE_RESULTADOS_REPORTE_TB RR
LEFT JOIN FIDE_REPORTES_TB R ON RR.ID_REPORTE = R.ID_REPORTE
LEFT JOIN FIDE_TIPO_REPORTE_TB TR ON R.ID_TIPO_REPORTE = TR.ID_TIPO_REPORTE
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_ROL_TB AS
SELECT R.ID_ROL,
       R.NOMBRE_ROL,
       E.NOMBRE AS ESTADO,
       R.FECHA_CREACION,
       R.FECHA_MODIFICACION,
       R.CREADO_POR,
       R.MODIFICADO_POR,
       R.ACCION
FROM FIDE_ROL_TB R
LEFT JOIN FIDE_ESTADO_TB E ON R.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_SERVICIO_TB AS
SELECT S.ID_SERVICIO,
       S.NOMBRE_SERVICIO,
       S.DESCRIPCION,
       S.VALOR_ESTIMADO,
       S.STOCK,
       C.NOMBRE AS CATEGORIA,
       E.NOMBRE AS ESTADO,
       S.IMAGEN_URL,
       S.FECHA_CREACION,
       S.FECHA_MODIFICACION,
       S.CREADO_POR,
       S.MODIFICADO_POR,
       S.ACCION
FROM FIDE_SERVICIO_TB S
LEFT JOIN FIDE_CATEGORIA_TB C ON S.ID_CATEGORIA = C.ID_CATEGORIA
LEFT JOIN FIDE_ESTADO_TB E ON S.ID_ESTADO = E.ID_ESTADO
/

CREATE OR REPLACE VIEW V_LISTAR_FIDE_TIPO_AHORRO_TB AS
SELECT T.ID_TIPO_AHORRO,
       T.NOMBRE,
       T.DESCRIPCION,
       E.NOMBRE AS ESTADO,
       T.FECHA_CREACION,
       T.FECHA_MODIFICACION,
       T.CREADO_POR,
       T.MODIFICADO_POR,
       T.ACCION
FROM FIDE_TIPO_AHORRO_TB T
LEFT JOIN FIDE_ESTADO_TB E ON T.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_TIPO_REPORTE_TB AS
SELECT T.ID_TIPO_REPORTE,
       T.NOMBRE,
       E.NOMBRE AS ESTADO,
       T.FECHA_CREACION,
       T.FECHA_MODIFICACION,
       T.CREADO_POR,
       T.MODIFICADO_POR,
       T.ACCION
FROM FIDE_TIPO_REPORTE_TB T
LEFT JOIN FIDE_ESTADO_TB E ON T.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_TIPO_TRANSACCION_TB AS
SELECT T.ID_TIPO_TRANSACCION,
       T.NOMBRE,
       T.DESCRIPCION,
       E.NOMBRE AS ESTADO,
       T.FECHA_CREACION,
       T.FECHA_MODIFICACION,
       T.CREADO_POR,
       T.MODIFICADO_POR,
       T.ACCION
FROM FIDE_TIPO_TRANSACCION_TB T
LEFT JOIN FIDE_ESTADO_TB E ON T.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_TRANSACCION_TB AS
SELECT T.ID_TRANSACCION,
       T.ID_USUARIO, 
       T.FECHA_TRANSACCION,
       TT.NOMBRE AS TIPO_TRANSACCION,
       T.MONTO_TOTAL,
       U.NOMBRE_USUARIO,
       E.NOMBRE AS ESTADO,
       T.FECHA_CREACION,
       T.FECHA_MODIFICACION,
       T.CREADO_POR,
       T.MODIFICADO_POR,
       T.ACCION
FROM FIDE_TRANSACCION_TB T
LEFT JOIN FIDE_TIPO_TRANSACCION_TB TT ON T.ID_TIPO_TRANSACCION = TT.ID_TIPO_TRANSACCION
LEFT JOIN FIDE_USUARIO_TB U ON T.ID_USUARIO = U.ID_USUARIO
LEFT JOIN FIDE_ESTADO_TB E ON T.ID_ESTADO = E.ID_ESTADO
/


CREATE OR REPLACE VIEW V_LISTAR_FIDE_USUARIOS_ROLES AS
SELECT UR.ID_USUARIO,
       U.NOMBRE_USUARIO,
       UR.ID_ROL,
       R.NOMBRE_ROL,
       UR.FECHA_CREACION,
       UR.FECHA_MODIFICACION,
       UR.CREADO_POR,
       UR.MODIFICADO_POR,
       UR.ACCION
FROM FIDE_USUARIOS_ROLES_TB UR
LEFT JOIN FIDE_USUARIO_TB U ON UR.ID_USUARIO = U.ID_USUARIO
LEFT JOIN FIDE_ROL_TB R ON UR.ID_ROL = R.ID_ROL
/

