--FUNCIÓN NUMÉRICA PARA REPORTES
CREATE OR REPLACE FUNCTION FIDE_SEQUENCIA_NUMERICA_REPORTE_FN
RETURN NUMBER AS
V_FECHA VARCHAR2(10);
V_VALOR NUMBER;
BEGIN
    V_FECHA := TO_CHAR(SYSDATE, 'DDMMYYYY');
    V_VALOR := TO_NUMBER(V_FECHA || LPAD(FIDE_REPORTES_SEQ.NEXTVAL, 7, 0));
    RETURN V_VALOR;
END;
/